import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Throne of Glass API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Throne of Glass API
        </h1>

        <p className={styles.description}>
          Query information about your favorie Throne of Glass Characters
        </p>

        <h1 className={styles.subtitle}>API Reference</h1>
        <a href="/api/characters" className={styles.card}>/api/characters</a>
        <a href="/api/characters?limit=5&skip=5" className={styles.card}>/api/characters?limit=5&skip=5</a>
        <a href="/api/characters/1" className={styles.card}>/api/characters/[id]</a>

      </main>
    </div>
  )
}

export default Home
